-- MySQL Script generated by MySQL Workbench
-- 03/24/17 20:44:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oqt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oqt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oqt` DEFAULT CHARACTER SET utf8 ;
USE `oqt` ;

-- -----------------------------------------------------
-- Table `oqt`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oqt`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oqt`.`Pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oqt`.`Pergunta` (
  `idPergunta` INT NOT NULL AUTO_INCREMENT,
  `pergunta` VARCHAR(45) NOT NULL,
  `solucao` VARCHAR(45) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idPergunta`, `Categoria_idCategoria`),
  INDEX `fk_Pergunta_Categoria_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Pergunta_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `oqt`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oqt`.`Solucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oqt`.`Solucao` (
  `idSolucao` INT NOT NULL AUTO_INCREMENT,
  `solucao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDiagnostico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oqt`.`Diagnostico_has_Pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oqt`.`Diagnostico_has_Pergunta` (
  `Diagnostico_idDiagnostico` INT NOT NULL,
  `Pergunta_idPergunta` INT NOT NULL,
  `Pergunta_Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Diagnostico_idDiagnostico`, `Pergunta_idPergunta`, `Pergunta_Categoria_idCategoria`),
  INDEX `fk_Diagnostico_has_Pergunta_Pergunta1_idx` (`Pergunta_idPergunta` ASC, `Pergunta_Categoria_idCategoria` ASC),
  INDEX `fk_Diagnostico_has_Pergunta_Diagnostico1_idx` (`Diagnostico_idDiagnostico` ASC),
  CONSTRAINT `fk_Diagnostico_has_Pergunta_Diagnostico1`
    FOREIGN KEY (`Diagnostico_idDiagnostico`)
    REFERENCES `oqt`.`Diagnostico` (`idDiagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnostico_has_Pergunta_Pergunta1`
    FOREIGN KEY (`Pergunta_idPergunta` , `Pergunta_Categoria_idCategoria`)
    REFERENCES `oqt`.`Pergunta` (`idPergunta` , `Categoria_idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
