-- MySQL Script generated by MySQL Workbench
-- 03/11/17 11:54:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OQT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OQT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OQT` DEFAULT CHARACTER SET utf8 ;
USE `OQT` ;

-- -----------------------------------------------------
-- Table `OQT`.`Doença`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OQT`.`Doença` (
  `idDoença` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDoença`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OQT`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OQT`.`Animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAnimal`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OQT`.`Animal_has_Doença`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OQT`.`Animal_has_Doença` (
  `Animal_idAnimal` INT NOT NULL,
  `Doença_idDoença` INT NOT NULL,
  PRIMARY KEY (`Animal_idAnimal`, `Doença_idDoença`),
  INDEX `fk_Animal_has_Doença_Doença1_idx` (`Doença_idDoença` ASC),
  INDEX `fk_Animal_has_Doença_Animal_idx` (`Animal_idAnimal` ASC),
  CONSTRAINT `fk_Animal_has_Doença_Animal`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `OQT`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_has_Doença_Doença1`
    FOREIGN KEY (`Doença_idDoença`)
    REFERENCES `OQT`.`Doença` (`idDoença`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OQT`.`Sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OQT`.`Sintomas` (
  `idSintomas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `especifico` INT(60) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idSintomas`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OQT`.`Doença_has_Sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OQT`.`Doença_has_Sintomas` (
  `Doença_idDoença` INT NOT NULL,
  `Sintomas_idSintomas` INT NOT NULL,
  PRIMARY KEY (`Doença_idDoença`, `Sintomas_idSintomas`),
  INDEX `fk_Doença_has_Sintomas_Sintomas1_idx` (`Sintomas_idSintomas` ASC),
  INDEX `fk_Doença_has_Sintomas_Doença1_idx` (`Doença_idDoença` ASC),
  CONSTRAINT `fk_Doença_has_Sintomas_Doença1`
    FOREIGN KEY (`Doença_idDoença`)
    REFERENCES `OQT`.`Doença` (`idDoença`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doença_has_Sintomas_Sintomas1`
    FOREIGN KEY (`Sintomas_idSintomas`)
    REFERENCES `OQT`.`Sintomas` (`idSintomas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
